name: pymc-tumoroscope
channels:
  - conda-forge
  - nvidia
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.10.*
  - aeppl
  - aesara
  - arviz=0.12.*
  - black
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - ipython
  - ipywidgets
  - isort
  - jax>=0.3.0
  - jaxlib>=0.3.0
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker
  - mamba
  - matplotlib>=3.5.0
  - mypy
  - nbconvert
  - nbformat
  - nbqa
  - nbterm
  - numpy>=1.22.0
  - numpyro=0.10.*
  - pandas>=1.3.0
  - pandoc
  - pip
  - pre-commit
  - pydantic
  - pyjanitor
  - pymc=4.2.*
  - python-graphviz
  - requests
  - seaborn
  - typer
  - watermark
  - xarray
  - pip:
    - python-dotenv
    - types-python-dateutil
